
class userNotFoundError(Exception):
    pass


class invaldPasswordError(Exception):
    pass
